version: '3'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    container_name: finance-db
    environment:
      MYSQL_ROOT_PASSWORD: dbmysql
      MYSQL_DATABASE: financedb
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'
